# Generated by Django 4.0.3 on 2022-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='preco',
        ),
    ]
