# Generated by Django 4.0.3 on 2022-03-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0002_remove_pdf_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lista_de_compras', to='pdfshare.usuario'),
        ),
    ]
