# Generated by Django 4.0.3 on 2022-03-30 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfshare', '0004_alter_pdf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='fileauthor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
