# Generated by Django 4.0.3 on 2022-03-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0005_alter_pdf_fileauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='usuario',
        ),
    ]
