# Generated by Django 4.0.3 on 2022-03-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0006_remove_pdf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='fileauthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pdfshare.usuario'),
        ),
    ]
