# Generated by Django 4.0.3 on 2022-03-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0007_alter_pdf_fileauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pdfshare.usuario')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pdfshare.pdf')),
            ],
        ),
    ]
