# Generated by Django 4.0.3 on 2022-04-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0008_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='preco',
            field=models.IntegerField(null=True),
        ),
    ]
