# Generated by Django 4.0.4 on 2022-04-26 00:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0009_transacao_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 21, 20, 28, 180041)),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to='images\\trabalho ESN', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
