# Generated by Django 4.0.4 on 2022-04-19 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0009_alter_pdf_filepath_alter_pdf_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='filepath',
            field=models.FileField(blank=True, help_text='Arquivo deve ser em formato PDF', upload_to='images\\trabalho ESN', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
