# Generated by Django 4.0.4 on 2022-04-26 01:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0010_pdf_status_usuario_download_count_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\ferib\\projeto_ESN\\PDFShare/pdfs', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 22, 58, 39, 790562)),
        ),
    ]
