# Generated by Django 4.0.4 on 2022-04-26 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfshare', '0011_alter_pdf_filepath_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 0, 0)),
        ),
    ]
